apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: lolero/docker-excercise-section-8-fib-calculator-client
      ports:
        - containerPort: 3000